runtime: python27
api_version: 1
threadsafe: true
service: api

handlers:
  - url: /_ah/api/.*
    script: main.api
    secure: always

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: latest

env_variables:
   ENDPOINTS_SERVICE_NAME: api.bjorneparkappen.appspot.com
   ENDPOINTS_SERVICE_VERSION: 2017-03-25r1
   FIREBASE_PROJECT_ID: 'bjorneparkappen'
