swagger: '2.0'
info:
  title: Bjorneparken API
  description: API for Bjorneparken
  version: "1.0.0"

host: bjorneparkappen.appspot.com

schemes:
  - https

basePath: /_ah/api/bjorneparkappen/v1
produces:
  - application/json

securityDefinitions:

  api_key:
    type: apiKey
    name: key
    in: query

security:
  - api_key: []

paths:
  /animals:
    get:
      summary: Animals
      operationId: animalsList
      description: |
        The Animals endpoint returns all active animals. The response includes each animal's information.
      security:
          - api_key: []
      tags:
        - Animals
      responses:
        200:
          description: An array of Animals
        401:
          description: Unauthorized
        default:
          description: Unexpected error
