/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-02-26 at 17:11:06 UTC 
 * Modify at your own risk.
 */

package none.bjorneparkappen_api.model;

/**
 * Model definition for MainAmenityRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bjorneparkappen_api. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainAmenityRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("amenity_type")
  private java.lang.String amenityType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> coordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainInternationalMessage> description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainInternationalMessage> label;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("visitor_destination")
  private java.lang.String visitorDestination;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAmenityType() {
    return amenityType;
  }

  /**
   * @param amenityType amenityType or {@code null} for none
   */
  public MainAmenityRequest setAmenityType(java.lang.String amenityType) {
    this.amenityType = amenityType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCoordinates() {
    return coordinates;
  }

  /**
   * @param coordinates coordinates or {@code null} for none
   */
  public MainAmenityRequest setCoordinates(java.util.List<java.lang.String> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MainInternationalMessage> getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public MainAmenityRequest setDescription(java.util.List<MainInternationalMessage> description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MainInternationalMessage> getLabel() {
    return label;
  }

  /**
   * @param label label or {@code null} for none
   */
  public MainAmenityRequest setLabel(java.util.List<MainInternationalMessage> label) {
    this.label = label;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVisitorDestination() {
    return visitorDestination;
  }

  /**
   * @param visitorDestination visitorDestination or {@code null} for none
   */
  public MainAmenityRequest setVisitorDestination(java.lang.String visitorDestination) {
    this.visitorDestination = visitorDestination;
    return this;
  }

  @Override
  public MainAmenityRequest set(String fieldName, Object value) {
    return (MainAmenityRequest) super.set(fieldName, value);
  }

  @Override
  public MainAmenityRequest clone() {
    return (MainAmenityRequest) super.clone();
  }

}
