/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-02-26 at 17:11:06 UTC 
 * Modify at your own risk.
 */

package none.bjorneparkappen_api.model;

/**
 * Model definition for MainEnclosureResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bjorneparkappen_api. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainEnclosureResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainAnimalResponse> animals;

  static {
    // hack to force ProGuard to consider MainAnimalResponse used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(MainAnimalResponse.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> coordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("visitor_destination")
  private java.lang.String visitorDestination;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MainAnimalResponse> getAnimals() {
    return animals;
  }

  /**
   * @param animals animals or {@code null} for none
   */
  public MainEnclosureResponse setAnimals(java.util.List<MainAnimalResponse> animals) {
    this.animals = animals;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCoordinates() {
    return coordinates;
  }

  /**
   * @param coordinates coordinates or {@code null} for none
   */
  public MainEnclosureResponse setCoordinates(java.util.List<java.lang.String> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MainEnclosureResponse setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * @param label label or {@code null} for none
   */
  public MainEnclosureResponse setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVisitorDestination() {
    return visitorDestination;
  }

  /**
   * @param visitorDestination visitorDestination or {@code null} for none
   */
  public MainEnclosureResponse setVisitorDestination(java.lang.String visitorDestination) {
    this.visitorDestination = visitorDestination;
    return this;
  }

  @Override
  public MainEnclosureResponse set(String fieldName, Object value) {
    return (MainEnclosureResponse) super.set(fieldName, value);
  }

  @Override
  public MainEnclosureResponse clone() {
    return (MainEnclosureResponse) super.clone();
  }

}
