/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-02-26 at 17:11:06 UTC 
 * Modify at your own risk.
 */

package none.bjorneparkappen_api.model;

/**
 * Model definition for ProtorpcMessagesCombinedContainer.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bjorneparkappen_api. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ProtorpcMessagesCombinedContainer extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainInternationalMessage> description;

  static {
    // hack to force ProGuard to consider MainInternationalMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(MainInternationalMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("enclosure_id") @com.google.api.client.json.JsonString
  private java.lang.Long enclosureId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("is_available")
  private java.lang.Boolean isAvailable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("species_id") @com.google.api.client.json.JsonString
  private java.lang.Long speciesId;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MainInternationalMessage> getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public ProtorpcMessagesCombinedContainer setDescription(java.util.List<MainInternationalMessage> description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEnclosureId() {
    return enclosureId;
  }

  /**
   * @param enclosureId enclosureId or {@code null} for none
   */
  public ProtorpcMessagesCombinedContainer setEnclosureId(java.lang.Long enclosureId) {
    this.enclosureId = enclosureId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsAvailable() {
    return isAvailable;
  }

  /**
   * @param isAvailable isAvailable or {@code null} for none
   */
  public ProtorpcMessagesCombinedContainer setIsAvailable(java.lang.Boolean isAvailable) {
    this.isAvailable = isAvailable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ProtorpcMessagesCombinedContainer setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSpeciesId() {
    return speciesId;
  }

  /**
   * @param speciesId speciesId or {@code null} for none
   */
  public ProtorpcMessagesCombinedContainer setSpeciesId(java.lang.Long speciesId) {
    this.speciesId = speciesId;
    return this;
  }

  @Override
  public ProtorpcMessagesCombinedContainer set(String fieldName, Object value) {
    return (ProtorpcMessagesCombinedContainer) super.set(fieldName, value);
  }

  @Override
  public ProtorpcMessagesCombinedContainer clone() {
    return (ProtorpcMessagesCombinedContainer) super.clone();
  }

}
