runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always
